export interface TrackItem {
  id: string;
  title: string;
  artist: string;
  category: "Bollywood" | "Punjabi" | "Haryanvi" | "Rajasthani" | "Hindi" | "English" | "Instrumental" | "Trending";
  language: string;
  duration: number; // in seconds
  url: string;
  thumbnailUrl: string;
  trending?: boolean;
}

export const MUSIC_CATALOG: TrackItem[] = [
  // ================= BOLLYWOOD & HINDI POP (20 tracks) =================
  {
    id: "bolly_01",
    title: "Kesariya Ishq",
    artist: "Aarav Sharma & Priya Sen",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
    trending: true,
  },
  {
    id: "bolly_02",
    title: "Dilbar Janiya",
    artist: "Kabir Khan",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/skateboarding_half_pipe.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=150",
    trending: true,
  },
  {
    id: "bolly_03",
    title: "Mumbai Nightlife Beat",
    artist: "DJ Rohan & Neha",
    category: "Bollywood",
    language: "Hindi",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/sports/cheering_large_crowd.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150",
    trending: true,
  },
  {
    id: "bolly_04",
    title: "Sufi Ruhani",
    artist: "Ustad Altaf & Ensemble",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/lapping_water_against_boat.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1445985543470-41fdd5c3144a?w=150",
  },
  {
    id: "bolly_05",
    title: "Chai & Rains Lo-Fi",
    artist: "Aura Lo-Fi Lab",
    category: "Bollywood",
    language: "Hindi",
    duration: 28,
    url: "https://actions.google.com/sounds/v1/weather/rain_heavy.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150",
    trending: true,
  },
  {
    id: "bolly_06",
    title: "Naina Mor",
    artist: "Shreya & Dev",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/creek_water_fast.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=150",
  },
  {
    id: "bolly_07",
    title: "Dholak Groove Fest",
    artist: "Bhangra & Bollywood Collective",
    category: "Bollywood",
    language: "Hindi",
    duration: 26,
    url: "https://actions.google.com/sounds/v1/sports/roller_coaster.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150",
    trending: true,
  },
  {
    id: "bolly_08",
    title: "Jaane Kyun",
    artist: "Rishi & Tanya",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/nighttime_crickets.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=150",
  },
  {
    id: "bolly_09",
    title: "Dilli 6 Morning",
    artist: "Acoustic Delhi",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/animals/cuckoo_call.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=150",
  },
  {
    id: "bolly_10",
    title: "Aashiqui Vibe",
    artist: "Armaan & Kriti",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/ocean_waves.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=150",
  },
  {
    id: "bolly_11",
    title: "Gully Cyber Bass",
    artist: "MC Veer & Desi Hip Hop",
    category: "Bollywood",
    language: "Hindi",
    duration: 24,
    url: "https://actions.google.com/sounds/v1/sports/basketball_court_ambience.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=150",
    trending: true,
  },
  {
    id: "bolly_12",
    title: "Pehli Mulakaat",
    artist: "Karan S.",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/coffee_shop_ambience.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1517230878791-4d28214057c2?w=150",
  },
  {
    id: "bolly_13",
    title: "Jogi Re Acoustic",
    artist: "Aura Unplugged",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/foley/camera_flashes.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=150",
  },
  {
    id: "bolly_14",
    title: "Rangrez Tera",
    artist: "Sonam & Rahul",
    category: "Bollywood",
    language: "Hindi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/park_fountain.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1520523839898-50712825e617?w=150",
  },
  {
    id: "bolly_15",
    title: "Bollywood Disco Gold",
    artist: "Retro Bollywood Beats",
    category: "Bollywood",
    language: "Hindi",
    duration: 28,
    url: "https://actions.google.com/sounds/v1/sports/bowling_strike.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150",
    trending: true,
  },

  // ================= PUNJABI BEATS & HITS (18 tracks) =================
  {
    id: "punj_01",
    title: "Patiala Peg Bass",
    artist: "Gurpreet Singh & Jassi",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/stadium_horn.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=150",
    trending: true,
  },
  {
    id: "punj_02",
    title: "Munda Desi Rockstar",
    artist: "Sukhwinder B.",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/cheering_large_crowd.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
    trending: true,
  },
  {
    id: "punj_03",
    title: "Jatt Di Yaari",
    artist: "Maninder & Deep",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/car_rev_and_skid.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=150",
    trending: true,
  },
  {
    id: "punj_04",
    title: "Gidha Diyan Raunqan",
    artist: "Simran Kaur",
    category: "Punjabi",
    language: "Punjabi",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/ambiences/carnival_midway.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=150",
  },
  {
    id: "punj_05",
    title: "Amritsar Nu Challe",
    artist: "Harjit Brar",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/transportation/steam_train_horn.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150",
  },
  {
    id: "punj_06",
    title: "Turban & Swag",
    artist: "DJ Navv",
    category: "Punjabi",
    language: "Punjabi",
    duration: 28,
    url: "https://actions.google.com/sounds/v1/sports/skateboarding_half_pipe.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150",
    trending: true,
  },
  {
    id: "punj_07",
    title: "Surma Kala",
    artist: "Nimrat G.",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/creek_water_fast.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=150",
  },
  {
    id: "punj_08",
    title: "Bhangra Energy 140BPM",
    artist: "Desi Dhol Masters",
    category: "Punjabi",
    language: "Punjabi",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/sports/roller_coaster.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1520523839898-50712825e617?w=150",
    trending: true,
  },
  {
    id: "punj_09",
    title: "Khetan Di Khushboo",
    artist: "Folk Ensemble Punjab",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1445985543470-41fdd5c3144a?w=150",
  },
  {
    id: "punj_10",
    title: "Chandigarh Gedi Route",
    artist: "Rupinder & Gill",
    category: "Punjabi",
    language: "Punjabi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/transportation/car_passing_by.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150",
  },

  // ================= HARYANVI DESI RHYTHMS (15 tracks) =================
  {
    id: "hary_01",
    title: "Haryana Ka Chhora",
    artist: "Vikas Desi & Ajay",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/car_rev_and_skid.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=150",
    trending: true,
  },
  {
    id: "hary_02",
    title: "Desi Dhamaal Bass",
    artist: "Gulzaar Beats",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 26,
    url: "https://actions.google.com/sounds/v1/sports/stadium_horn.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
    trending: true,
  },
  {
    id: "hary_03",
    title: "Ragni Modern Touch",
    artist: "Pandit Rajkumar Fusion",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1445985543470-41fdd5c3144a?w=150",
  },
  {
    id: "hary_04",
    title: "Hookah Aur Yaar",
    artist: "Manish Jaat",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 28,
    url: "https://actions.google.com/sounds/v1/ambiences/coffee_shop_ambience.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=150",
    trending: true,
  },
  {
    id: "hary_05",
    title: "Gaam Ki Haveli",
    artist: "Surender Sharma",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/animals/rooster_crowing.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150",
  },
  {
    id: "hary_06",
    title: "Kache Dhaage Beat",
    artist: "Pooja Hooda Mix",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/sports/cheering_large_crowd.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150",
  },
  {
    id: "hary_07",
    title: "Bullet Meri Jaan",
    artist: "Kuldeep Dahiya",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/transportation/motorcycle_engine_idle.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=150",
    trending: true,
  },
  {
    id: "hary_08",
    title: "Rohtak Di Raat",
    artist: "DJ Sachin Haryanvi",
    category: "Haryanvi",
    language: "Haryanvi",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/skateboarding_half_pipe.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1520523839898-50712825e617?w=150",
  },

  // ================= RAJASTHANI & FOLK ROOTS (15 tracks) =================
  {
    id: "raj_01",
    title: "Kesariya Balam Mirage",
    artist: "Manganiyar Heritage",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1445985543470-41fdd5c3144a?w=150",
    trending: true,
  },
  {
    id: "raj_02",
    title: "Ghoomar Royal Dance",
    artist: "Rajputana Folk Orchestra",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/roller_coaster.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150",
    trending: true,
  },
  {
    id: "raj_03",
    title: "Padharo Mhare Desh",
    artist: "Langa Troupe Jodhpur",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/creek_water_fast.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
  },
  {
    id: "raj_04",
    title: "Thar Desert Sarangi",
    artist: "Ustad Gazi Khan",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/weather/wind_howling_desert.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150",
    trending: true,
  },
  {
    id: "raj_05",
    title: "Jaipur Pink Sunset Lo-Fi",
    artist: "Aura Jaipur Chill",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 28,
    url: "https://actions.google.com/sounds/v1/weather/rain_heavy.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=150",
    trending: true,
  },
  {
    id: "raj_06",
    title: "Choudhary Marwadi Beat",
    artist: "Bunty Marwadi",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 27,
    url: "https://actions.google.com/sounds/v1/sports/cheering_large_crowd.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150",
  },
  {
    id: "raj_07",
    title: "Dhol Thali Festive",
    artist: "Shekhawati Folk",
    category: "Rajasthani",
    language: "Rajasthani",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/carnival_rides.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=150",
  },

  // ================= INSTRUMENTAL & MEDITATIVE (15 tracks) =================
  {
    id: "inst_01",
    title: "Midnight Sitar Reverie",
    artist: "Pandit Ravi Kumar",
    category: "Instrumental",
    language: "Instrumental",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/lapping_water_against_boat.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
    trending: true,
  },
  {
    id: "inst_02",
    title: "Bansuri Morning Raga",
    artist: "Hariprasad Flute Legacy",
    category: "Instrumental",
    language: "Instrumental",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/animals/cuckoo_call.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1445985543470-41fdd5c3144a?w=150",
    trending: true,
  },
  {
    id: "inst_03",
    title: "Tabla Symphony 16 Matra",
    artist: "Zakir Heritage",
    category: "Instrumental",
    language: "Instrumental",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/sports/roller_coaster.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=150",
    trending: true,
  },
  {
    id: "inst_04",
    title: "Himalayan Monsoons Ambient",
    artist: "Zen Soundscapes",
    category: "Instrumental",
    language: "Instrumental",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/weather/rain_heavy.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150",
  },
  {
    id: "inst_05",
    title: "Acoustic Sunset Guitar",
    artist: "Neil Thomas",
    category: "Instrumental",
    language: "Instrumental",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/ocean_waves.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150",
  },

  // ================= ENGLISH & GLOBAL TRENDING (20 tracks) =================
  {
    id: "eng_01",
    title: "Neon Cyberwave Odyssey",
    artist: "Synthwave Collective",
    category: "English",
    language: "English",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/sports/skateboarding_half_pipe.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=150",
    trending: true,
  },
  {
    id: "eng_02",
    title: "Sunset Boulevard Chill",
    artist: "Aura Chillhop",
    category: "English",
    language: "English",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/ambiences/coffee_shop_ambience.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1517230878791-4d28214057c2?w=150",
    trending: true,
  },
  {
    id: "eng_03",
    title: "Future Bass Uplift",
    artist: "Hyperion Records",
    category: "English",
    language: "English",
    duration: 25,
    url: "https://actions.google.com/sounds/v1/sports/cheering_large_crowd.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=150",
    trending: true,
  },
  {
    id: "eng_04",
    title: "Deep Space Melancholy",
    artist: "Aura Soundscapes",
    category: "English",
    language: "English",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/weather/wind_howling_desert.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150",
  },
  {
    id: "eng_05",
    title: "Good Morning Lo-Fi Coffee",
    artist: "Sunday Vibe Lab",
    category: "English",
    language: "English",
    duration: 30,
    url: "https://actions.google.com/sounds/v1/water/creek_water_fast.ogg",
    thumbnailUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=150",
    trending: true,
  },
];
