import { NextResponse } from 'next/server';

export async function GET() {
  const trendingTopics = [
    {
      id: 'trend_1',
      rank: 1,
      name: '#AI',
      category: 'Artificial Intelligence',
      postsCount: '12.4K',
      viewsCount: '2.8M',
      likesCount: '540K',
      commentsCount: '84K',
      sharesCount: '32K',
      engagementRate: '14.2%',
      growthRate: '+184%',
      isRising: true,
      trendingScore: 96,
      authenticEngagement: '94%',
      isBlockchainVerified: true,
    },
    {
      id: 'trend_2',
      rank: 2,
      name: '#Blockchain',
      category: 'Web3 & Crypto',
      postsCount: '8.7K',
      viewsCount: '1.6M',
      likesCount: '310K',
      commentsCount: '42K',
      sharesCount: '18K',
      engagementRate: '12.8%',
      growthRate: '+127%',
      isRising: true,
      trendingScore: 92,
      authenticEngagement: '92%',
      isBlockchainVerified: true,
    },
    {
      id: 'trend_3',
      rank: 3,
      name: '#AIAgents',
      category: 'Autonomous Tech',
      postsCount: '6.2K',
      viewsCount: '1.1M',
      likesCount: '215K',
      commentsCount: '29K',
      sharesCount: '14K',
      engagementRate: '11.5%',
      growthRate: '+210%',
      isRising: true,
      trendingScore: 94,
      authenticEngagement: '95%',
      isBlockchainVerified: true,
    },
    {
      id: 'trend_4',
      rank: 4,
      name: '#DeFi',
      category: 'Decentralized Finance',
      postsCount: '5.1K',
      viewsCount: '950K',
      likesCount: '180K',
      commentsCount: '21K',
      sharesCount: '9K',
      engagementRate: '9.8%',
      growthRate: '+85%',
      isRising: false,
      trendingScore: 88,
      authenticEngagement: '90%',
      isBlockchainVerified: true,
    },
    {
      id: 'trend_5',
      rank: 5,
      name: '#Solidity',
      category: 'Smart Contracts',
      postsCount: '3.9K',
      viewsCount: '620K',
      likesCount: '112K',
      commentsCount: '15K',
      sharesCount: '7K',
      engagementRate: '8.9%',
      growthRate: '+64%',
      isRising: false,
      trendingScore: 84,
      authenticEngagement: '93%',
      isBlockchainVerified: true,
    },
  ];

  const contentOpportunities = [
    {
      id: 'opp_1',
      topic: 'AI Agents & Automation',
      bestContent: 'Short Reel / Tutorial / Demo',
      expectedReach: 'Very High 🔥',
      competition: 'Medium',
      currentDemand: 'Extreme',
      suggestedHashtags: '#AIAgents #AI #Tech #Automation',
      trendingScore: 96,
      topicTag: 'AIAgents',
    },
    {
      id: 'opp_2',
      topic: 'Layer-2 Ethereum Scaling',
      bestContent: 'Infographic / News / Breakdown',
      expectedReach: 'High',
      competition: 'Low',
      currentDemand: 'High',
      suggestedHashtags: '#Ethereum #Layer2 #CryptoNews',
      trendingScore: 91,
      topicTag: 'Ethereum',
    },
    {
      id: 'opp_3',
      topic: 'Proof-of-Creation NFTs',
      bestContent: 'Behind the Scenes / Artwork Reveal',
      expectedReach: 'High',
      competition: 'Medium',
      currentDemand: 'High',
      suggestedHashtags: '#ProofOfCreation #NFT #DigitalArt',
      trendingScore: 89,
      topicTag: 'NFT',
    },
  ];

  const trendingReels = [
    {
      id: 'reel_1',
      creator: 'Elena Rostova',
      creatorUsername: '@elena_vibe',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
      views: '450K',
      likes: '89K',
      comments: '3.4K',
      shares: '1.2K',
      engagementRate: '15.4%',
      growthRate: '+240%',
      trendingScore: 98,
      title: 'Building Autonomous AI Agents in 60 Seconds 🤖✨',
      isBlockchainVerified: true,
    },
    {
      id: 'reel_2',
      creator: 'Liam Vance',
      creatorUsername: '@liam_explorer',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      mediaUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
      views: '320K',
      likes: '62K',
      comments: '2.1K',
      shares: '850',
      engagementRate: '13.1%',
      growthRate: '+165%',
      trendingScore: 94,
      title: 'Cosmic Landscape Photography & On-Chain Proof 🌌',
      isBlockchainVerified: true,
    },
  ];

  return NextResponse.json({
    success: true,
    trendingTopics,
    contentOpportunities,
    trendingReels,
    meta: {
      overallAuthenticity: '93%',
      activeMonitoredPosts: 45200,
      blockchainSyncStatus: 'Synced to Hardhat Node (Chain 31337)',
      updatedAt: new Date().toISOString(),
    },
  });
}
